// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using in_houseLPIWeb.Data;

namespace in_houseLPIWeb.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20240829061516_SyncDatabaseWithModel")]
    partial class SyncDatabaseWithModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("in_houseLPIWeb.Model.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeptHead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.Payee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PayeeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayeeDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Payees");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Archive")
                        .HasColumnType("bit");

                    b.Property<bool>("IFC_Index")
                        .HasColumnType("bit");

                    b.Property<bool>("Index")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RFP_Activate")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_Add")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_Archive")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_Dash")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_Index")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_PoP_Delete")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_PoP_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_Print")
                        .HasColumnType("bit");

                    b.Property<bool>("RFP_View")
                        .HasColumnType("bit");

                    b.Property<bool>("RFPutil_Dash")
                        .HasColumnType("bit");

                    b.Property<bool>("RFPutil_Payee_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("RFPutil_Payee_Index")
                        .HasColumnType("bit");

                    b.Property<bool>("RFPutil_TOC_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("RFPutil_TOC_Index")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Util_Dash")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_Permission")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_StoreEnt_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_StoreEnt_Index")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_StoreType_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_StoreType_Index")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_Store_Actv")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_Store_Archive")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_Store_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_Store_Index")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_UserDep_Actv")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_UserDep_Archive")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_UserDep_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_UserDep_Index")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_User_Edit")
                        .HasColumnType("bit");

                    b.Property<bool>("Util_User_Index")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.PoPList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ApVoucher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdjNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CoverEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CoverStartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DR_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Entity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OR_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PO_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoP_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SI_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceInvoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VATPercent")
                        .HasColumnType("int");

                    b.Property<int>("WHTPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PoP");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<decimal>("MRC")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("date");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSDWAN")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.StoreType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoreTypes");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.TOC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("TOCDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOCName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOCdescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TOCs");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("in_houseLPIWeb.Model.rfpForm", b =>
                {
                    b.Property<int>("RFP_No")
                        .HasColumnType("int");

                    b.Property<string>("Approved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Checked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoPCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RFP_No");

                    b.ToTable("rfpForms");
                });
#pragma warning restore 612, 618
        }
    }
}
